version: 2
build:
    image: testing
python:
    version: 3.10
    install:
        - requirements: docs/requirements.txt
    system_packages: false
sphinx:
    builder: html
    configuration: docs/conf.py
