version: 2
build:
    image: latest
python:
    version: '3.9'
    install:
        - requirements: docs/requirements.txt
    system_packages: false
sphinx:
    builder: html
    configuration: docs/conf.py
