version: 2
build:
    os: ubuntu-22.04
    tools:
      python: '3.10'
    jobs:
      post_install:
        - pip install --no-cache-dir poetry
        - pip uninstall -y sphinx
        - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: true
