on:
  push:
    tags: ['*']
name: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: 1.5.1
    - name: Deploy to PyPI
      run: poetry publish --build
      env:
        POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{secrets.PYPI_TOKEN}}
