on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
name: tests
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{runner.os}}-poetry-${{hashFiles('poetry.lock')}}
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: 1.3.1
      - name: Install dependencies
        run: poetry install
      - name: Lint project
        run: >-
          poetry run pylint yaenv &&
          poetry run mypy -p yaenv &&
          poetry run pydocstyle yaenv
      - name: Run tests
        run: poetry run pytest --cov-report=xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
