on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
name: tests
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{runner.os}}-poetry-${{hashFiles('poetry.lock')}}
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python}}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.3
      - name: Install dependencies
        run: poetry install
      - name: Lint project
        run: >-
          poetry run ruff check yaenv &&
          poetry run mypy -p yaenv
      - name: Run tests
        run: poetry run pytest --cov-report=xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
